export interface ThemeStyles {
  pageBg: string
  cardClass: string
  headerBg: string
  headerText: string
  headerSub: string
  annBg: string
  annText: string
  annIcon: string
  planSelectedBorder: string
  planSelectedBg: string
  planBorder: string
  planBg: string
  planTitle: string
  planSub: string
  planPrice: string
  planPopularBg: string
  planPopularText: string
  inputBorder: string
  inputBg: string
  inputText: string
  inputPlaceholder: string
  ctaBg: string
  ctaText: string
  ctaHover: string
  bodyText: string
  mutedText: string
  footerText: string
  errorBg: string
  errorText: string
  successBg: string
  successPageBg: string
  // Layout variations
  layoutType: "grid" | "list" | "featured" | "compact"
  // Structural variations
  headerStyle: "centered" | "left-aligned" | "large-hero" | "minimal"
  cardShape: "rounded-2xl" | "rounded-3xl" | "rounded-none" | "rounded-lg"
  ctaStyle: "full-width" | "centered" | "pill"
  showPhoneBeforePlans: boolean
  showWifiIcon: boolean
}

export function getTheme(id: number): ThemeStyles {
  switch (id) {
    case 2: // Dark Mode - Featured Layout (Cyberpunk style)
      return {
        layoutType: "featured",
        headerStyle: "large-hero",
        cardShape: "rounded-2xl",
        ctaStyle: "full-width",
        showPhoneBeforePlans: false,
        showWifiIcon: true,
        pageBg: "min-h-screen bg-gradient-to-br from-gray-950 via-gray-900 to-gray-800",
        cardClass: "bg-gray-900/80 backdrop-blur-xl border border-gray-700/50 rounded-2xl shadow-2xl",
        headerBg: "bg-gradient-to-r from-cyan-600 to-blue-600",
        headerText: "text-white",
        headerSub: "text-cyan-100/80",
        annBg: "bg-cyan-950/40 border border-cyan-700/30",
        annText: "text-cyan-200",
        annIcon: "text-cyan-400",
        planSelectedBorder: "border-cyan-500",
        planSelectedBg: "bg-cyan-950/40",
        planBorder: "border-gray-700/50",
        planBg: "bg-gray-800/50",
        planTitle: "text-white",
        planSub: "text-gray-400",
        planPrice: "text-cyan-400",
        planPopularBg: "bg-cyan-500",
        planPopularText: "text-white",
        inputBorder: "border-gray-600",
        inputBg: "bg-gray-800",
        inputText: "text-white",
        inputPlaceholder: "placeholder:text-gray-500",
        ctaBg: "bg-cyan-500 hover:bg-cyan-400",
        ctaText: "text-white",
        ctaHover: "hover:shadow-cyan-500/25",
        bodyText: "text-gray-200",
        mutedText: "text-gray-400",
        footerText: "text-gray-600",
        errorBg: "bg-red-950/40 border-red-700/30",
        errorText: "text-red-400",
        successBg: "bg-emerald-950/40",
        successPageBg: "min-h-screen bg-gradient-to-br from-gray-950 via-gray-900 to-gray-800",
      }
    case 3: // Gradient - List Layout (Vibrant gradient style)
      return {
        layoutType: "list",
        headerStyle: "centered",
        cardShape: "rounded-3xl",
        ctaStyle: "pill",
        showPhoneBeforePlans: true,
        showWifiIcon: true,
        pageBg: "min-h-screen bg-gradient-to-br from-purple-700 via-fuchsia-600 to-pink-500",
        cardClass: "bg-white/95 backdrop-blur-sm rounded-2xl shadow-2xl",
        headerBg: "bg-gradient-to-r from-purple-600 to-pink-500",
        headerText: "text-white",
        headerSub: "text-purple-100/80",
        annBg: "bg-purple-50 border border-purple-200",
        annText: "text-purple-700",
        annIcon: "text-purple-500",
        planSelectedBorder: "border-purple-500",
        planSelectedBg: "bg-purple-50",
        planBorder: "border-gray-200",
        planBg: "bg-white",
        planTitle: "text-gray-900",
        planSub: "text-gray-500",
        planPrice: "text-purple-600",
        planPopularBg: "bg-purple-500",
        planPopularText: "text-white",
        inputBorder: "border-gray-300",
        inputBg: "bg-white",
        inputText: "text-gray-900",
        inputPlaceholder: "placeholder:text-gray-400",
        ctaBg: "bg-gradient-to-r from-purple-600 to-pink-500 hover:from-purple-700 hover:to-pink-600",
        ctaText: "text-white",
        ctaHover: "hover:shadow-purple-500/25",
        bodyText: "text-gray-700",
        mutedText: "text-gray-500",
        footerText: "text-gray-400",
        errorBg: "bg-red-50 border-red-200",
        errorText: "text-red-700",
        successBg: "bg-green-50",
        successPageBg: "min-h-screen bg-gradient-to-br from-emerald-600 to-teal-500",
      }
    case 4: // Minimal - Compact Layout (Clean, Apple-like)
      return {
        layoutType: "compact",
        headerStyle: "minimal",
        cardShape: "rounded-lg",
        ctaStyle: "full-width",
        showPhoneBeforePlans: false,
        showWifiIcon: false,
        pageBg: "min-h-screen bg-white",
        cardClass: "bg-white rounded-2xl shadow-sm border border-gray-100",
        headerBg: "bg-white border-b border-gray-100",
        headerText: "text-gray-900",
        headerSub: "text-gray-500",
        annBg: "bg-gray-50 border border-gray-200",
        annText: "text-gray-700",
        annIcon: "text-gray-500",
        planSelectedBorder: "border-gray-900",
        planSelectedBg: "bg-gray-50",
        planBorder: "border-gray-200",
        planBg: "bg-white",
        planTitle: "text-gray-900",
        planSub: "text-gray-500",
        planPrice: "text-gray-900",
        planPopularBg: "bg-gray-900",
        planPopularText: "text-white",
        inputBorder: "border-gray-300",
        inputBg: "bg-white",
        inputText: "text-gray-900",
        inputPlaceholder: "placeholder:text-gray-400",
        ctaBg: "bg-gray-900 hover:bg-gray-800",
        ctaText: "text-white",
        ctaHover: "",
        bodyText: "text-gray-700",
        mutedText: "text-gray-400",
        footerText: "text-gray-300",
        errorBg: "bg-red-50 border-red-200",
        errorText: "text-red-700",
        successBg: "bg-green-50",
        successPageBg: "min-h-screen bg-white",
      }
    case 5: // Vibrant - Grid Layout (Energetic, event-poster style)
      return {
        layoutType: "grid",
        headerStyle: "large-hero",
        cardShape: "rounded-2xl",
        ctaStyle: "pill",
        showPhoneBeforePlans: false,
        showWifiIcon: true,
        pageBg: "min-h-screen bg-gradient-to-br from-amber-400 via-orange-500 to-red-500",
        cardClass: "bg-white rounded-2xl shadow-2xl",
        headerBg: "bg-gradient-to-r from-amber-500 to-orange-500",
        headerText: "text-white",
        headerSub: "text-amber-100/80",
        annBg: "bg-amber-50 border border-amber-200",
        annText: "text-amber-800",
        annIcon: "text-amber-600",
        planSelectedBorder: "border-orange-500",
        planSelectedBg: "bg-orange-50",
        planBorder: "border-gray-200",
        planBg: "bg-white",
        planTitle: "text-gray-900",
        planSub: "text-gray-500",
        planPrice: "text-orange-600",
        planPopularBg: "bg-orange-500",
        planPopularText: "text-white",
        inputBorder: "border-gray-300",
        inputBg: "bg-white",
        inputText: "text-gray-900",
        inputPlaceholder: "placeholder:text-gray-400",
        ctaBg: "bg-orange-500 hover:bg-orange-600",
        ctaText: "text-white",
        ctaHover: "hover:shadow-orange-500/25",
        bodyText: "text-gray-700",
        mutedText: "text-gray-500",
        footerText: "text-gray-400",
        errorBg: "bg-red-50 border-red-200",
        errorText: "text-red-700",
        successBg: "bg-green-50",
        successPageBg: "min-h-screen bg-gradient-to-br from-emerald-400 to-green-500",
      }
    case 6: // Corporate - Featured Layout (Enterprise, boardroom style)
      return {
        layoutType: "featured",
        headerStyle: "left-aligned",
        cardShape: "rounded-lg",
        ctaStyle: "full-width",
        showPhoneBeforePlans: true,
        showWifiIcon: false,
        pageBg: "min-h-screen bg-gradient-to-b from-slate-50 to-slate-200",
        cardClass: "bg-white rounded-2xl shadow-lg border border-slate-200",
        headerBg: "bg-slate-800",
        headerText: "text-white",
        headerSub: "text-slate-300",
        annBg: "bg-slate-50 border border-slate-200",
        annText: "text-slate-700",
        annIcon: "text-slate-500",
        planSelectedBorder: "border-slate-700",
        planSelectedBg: "bg-slate-50",
        planBorder: "border-slate-200",
        planBg: "bg-white",
        planTitle: "text-slate-900",
        planSub: "text-slate-500",
        planPrice: "text-slate-800",
        planPopularBg: "bg-slate-700",
        planPopularText: "text-white",
        inputBorder: "border-slate-300",
        inputBg: "bg-white",
        inputText: "text-slate-900",
        inputPlaceholder: "placeholder:text-slate-400",
        ctaBg: "bg-slate-800 hover:bg-slate-700",
        ctaText: "text-white",
        ctaHover: "",
        bodyText: "text-slate-700",
        mutedText: "text-slate-400",
        footerText: "text-slate-400",
        errorBg: "bg-red-50 border-red-200",
        errorText: "text-red-700",
        successBg: "bg-green-50",
        successPageBg: "min-h-screen bg-gradient-to-b from-emerald-50 to-emerald-100",
      }
    case 7: // Glass - List Layout (Glassmorphism, futuristic)
      return {
        layoutType: "list",
        headerStyle: "centered",
        cardShape: "rounded-3xl",
        ctaStyle: "centered",
        showPhoneBeforePlans: false,
        showWifiIcon: true,
        pageBg: "min-h-screen bg-gradient-to-br from-teal-500 via-cyan-500 to-blue-600",
        cardClass: "bg-white/15 backdrop-blur-2xl border border-white/20 rounded-2xl shadow-2xl",
        headerBg: "bg-white/10",
        headerText: "text-white",
        headerSub: "text-white/70",
        annBg: "bg-white/10 border border-white/15",
        annText: "text-white/90",
        annIcon: "text-white/70",
        planSelectedBorder: "border-white/60",
        planSelectedBg: "bg-white/15",
        planBorder: "border-white/15",
        planBg: "bg-white/5",
        planTitle: "text-white",
        planSub: "text-white/60",
        planPrice: "text-white",
        planPopularBg: "bg-white/25",
        planPopularText: "text-white",
        inputBorder: "border-white/20",
        inputBg: "bg-white/10",
        inputText: "text-white",
        inputPlaceholder: "placeholder:text-white/40",
        ctaBg: "bg-white hover:bg-white/90",
        ctaText: "text-teal-700 font-bold",
        ctaHover: "hover:shadow-white/20",
        bodyText: "text-white/80",
        mutedText: "text-white/50",
        footerText: "text-white/30",
        errorBg: "bg-red-500/20 border-red-400/30",
        errorText: "text-red-200",
        successBg: "bg-emerald-500/20",
        successPageBg: "min-h-screen bg-gradient-to-br from-emerald-500 via-teal-500 to-cyan-600",
      }
    case 8: // Neon Noir
      return {
        layoutType: "grid",
        headerStyle: "centered",
        cardShape: "rounded-2xl",
        ctaStyle: "full-width",
        showPhoneBeforePlans: false,
        showWifiIcon: true,
        pageBg: "min-h-screen bg-gray-950",
        cardClass: "bg-gray-900 border border-violet-500/20 rounded-2xl shadow-2xl shadow-violet-900/20",
        headerBg: "bg-gradient-to-r from-violet-900 to-purple-900",
        headerText: "text-white",
        headerSub: "text-violet-300/70",
        annBg: "bg-violet-950/50 border border-violet-700/30",
        annText: "text-violet-200",
        annIcon: "text-violet-400",
        planSelectedBorder: "border-violet-500",
        planSelectedBg: "bg-violet-950/40",
        planBorder: "border-gray-700/50",
        planBg: "bg-gray-800/60",
        planTitle: "text-white",
        planSub: "text-gray-400",
        planPrice: "text-violet-400",
        planPopularBg: "bg-violet-500",
        planPopularText: "text-white",
        inputBorder: "border-gray-700",
        inputBg: "bg-gray-800",
        inputText: "text-white",
        inputPlaceholder: "placeholder:text-gray-600",
        ctaBg: "bg-gradient-to-r from-violet-600 to-purple-600 hover:from-violet-500 hover:to-purple-500",
        ctaText: "text-white",
        ctaHover: "hover:shadow-violet-500/30",
        bodyText: "text-gray-300",
        mutedText: "text-gray-500",
        footerText: "text-gray-700",
        errorBg: "bg-red-950/40 border-red-700/30",
        errorText: "text-red-400",
        successBg: "bg-violet-950/40",
        successPageBg: "min-h-screen bg-gray-950",
      }
    case 9: // Safari Warmth
      return {
        layoutType: "list",
        headerStyle: "left-aligned",
        cardShape: "rounded-2xl",
        ctaStyle: "full-width",
        showPhoneBeforePlans: false,
        showWifiIcon: false,
        pageBg: "min-h-screen bg-amber-50",
        cardClass: "bg-white rounded-2xl shadow-lg border border-amber-100",
        headerBg: "bg-amber-800",
        headerText: "text-amber-50",
        headerSub: "text-amber-200",
        annBg: "bg-amber-100 border border-amber-300",
        annText: "text-amber-900",
        annIcon: "text-amber-700",
        planSelectedBorder: "border-amber-700",
        planSelectedBg: "bg-amber-50",
        planBorder: "border-amber-100",
        planBg: "bg-white",
        planTitle: "text-gray-900",
        planSub: "text-amber-700",
        planPrice: "text-amber-800",
        planPopularBg: "bg-amber-700",
        planPopularText: "text-white",
        inputBorder: "border-amber-200",
        inputBg: "bg-white",
        inputText: "text-gray-900",
        inputPlaceholder: "placeholder:text-amber-300",
        ctaBg: "bg-amber-700 hover:bg-amber-800",
        ctaText: "text-white",
        ctaHover: "",
        bodyText: "text-gray-700",
        mutedText: "text-amber-600",
        footerText: "text-amber-300",
        errorBg: "bg-red-50 border-red-200",
        errorText: "text-red-700",
        successBg: "bg-green-50",
        successPageBg: "min-h-screen bg-amber-50",
      }
    case 10: // Ocean Breeze
      return {
        layoutType: "grid",
        headerStyle: "large-hero",
        cardShape: "rounded-2xl",
        ctaStyle: "pill",
        showPhoneBeforePlans: false,
        showWifiIcon: true,
        pageBg: "min-h-screen bg-gradient-to-b from-sky-400 to-teal-500",
        cardClass: "bg-white/95 rounded-2xl shadow-2xl",
        headerBg: "bg-gradient-to-r from-sky-500 to-teal-500",
        headerText: "text-white",
        headerSub: "text-sky-100",
        annBg: "bg-sky-50 border border-sky-200",
        annText: "text-sky-800",
        annIcon: "text-sky-500",
        planSelectedBorder: "border-teal-500",
        planSelectedBg: "bg-teal-50",
        planBorder: "border-gray-200",
        planBg: "bg-white",
        planTitle: "text-gray-900",
        planSub: "text-gray-500",
        planPrice: "text-teal-600",
        planPopularBg: "bg-teal-500",
        planPopularText: "text-white",
        inputBorder: "border-gray-200",
        inputBg: "bg-white",
        inputText: "text-gray-900",
        inputPlaceholder: "placeholder:text-gray-400",
        ctaBg: "bg-teal-500 hover:bg-teal-600",
        ctaText: "text-white",
        ctaHover: "hover:shadow-teal-500/25",
        bodyText: "text-gray-700",
        mutedText: "text-gray-500",
        footerText: "text-gray-400",
        errorBg: "bg-red-50 border-red-200",
        errorText: "text-red-700",
        successBg: "bg-teal-50",
        successPageBg: "min-h-screen bg-gradient-to-b from-sky-400 to-teal-500",
      }
    case 11: // Midnight Luxury
      return {
        layoutType: "featured",
        headerStyle: "centered",
        cardShape: "rounded-2xl",
        ctaStyle: "full-width",
        showPhoneBeforePlans: true,
        showWifiIcon: false,
        pageBg: "min-h-screen bg-slate-900",
        cardClass: "bg-slate-800 border border-yellow-500/10 rounded-2xl shadow-2xl",
        headerBg: "bg-gradient-to-r from-slate-900 to-slate-800 border-b border-yellow-500/20",
        headerText: "text-yellow-400",
        headerSub: "text-slate-400",
        annBg: "bg-yellow-950/30 border border-yellow-700/30",
        annText: "text-yellow-200",
        annIcon: "text-yellow-500",
        planSelectedBorder: "border-yellow-500",
        planSelectedBg: "bg-yellow-950/20",
        planBorder: "border-slate-700",
        planBg: "bg-slate-700/50",
        planTitle: "text-white",
        planSub: "text-slate-400",
        planPrice: "text-yellow-400",
        planPopularBg: "bg-yellow-500",
        planPopularText: "text-slate-900",
        inputBorder: "border-slate-600",
        inputBg: "bg-slate-700",
        inputText: "text-white",
        inputPlaceholder: "placeholder:text-slate-500",
        ctaBg: "bg-gradient-to-r from-yellow-500 to-amber-500 hover:from-yellow-400 hover:to-amber-400",
        ctaText: "text-slate-900 font-bold",
        ctaHover: "hover:shadow-yellow-500/20",
        bodyText: "text-slate-300",
        mutedText: "text-slate-500",
        footerText: "text-slate-700",
        errorBg: "bg-red-950/40 border-red-700/30",
        errorText: "text-red-400",
        successBg: "bg-yellow-950/30",
        successPageBg: "min-h-screen bg-slate-900",
      }
    case 12: // Blossom
      return {
        layoutType: "list",
        headerStyle: "centered",
        cardShape: "rounded-3xl",
        ctaStyle: "pill",
        showPhoneBeforePlans: false,
        showWifiIcon: true,
        pageBg: "min-h-screen bg-gradient-to-br from-rose-50 to-pink-100",
        cardClass: "bg-white rounded-3xl shadow-xl border border-pink-100",
        headerBg: "bg-gradient-to-r from-pink-400 to-rose-400",
        headerText: "text-white",
        headerSub: "text-pink-100",
        annBg: "bg-pink-50 border border-pink-200",
        annText: "text-pink-700",
        annIcon: "text-pink-400",
        planSelectedBorder: "border-pink-400",
        planSelectedBg: "bg-pink-50",
        planBorder: "border-pink-100",
        planBg: "bg-white",
        planTitle: "text-gray-900",
        planSub: "text-gray-400",
        planPrice: "text-pink-500",
        planPopularBg: "bg-pink-400",
        planPopularText: "text-white",
        inputBorder: "border-pink-200",
        inputBg: "bg-white",
        inputText: "text-gray-900",
        inputPlaceholder: "placeholder:text-pink-300",
        ctaBg: "bg-gradient-to-r from-pink-400 to-rose-400 hover:from-pink-500 hover:to-rose-500",
        ctaText: "text-white",
        ctaHover: "hover:shadow-pink-400/25",
        bodyText: "text-gray-700",
        mutedText: "text-gray-400",
        footerText: "text-pink-200",
        errorBg: "bg-red-50 border-red-200",
        errorText: "text-red-700",
        successBg: "bg-pink-50",
        successPageBg: "min-h-screen bg-gradient-to-br from-rose-50 to-pink-100",
      }
    case 13: // Neumorphic - Soft, embossed clock-app style
      return {
        layoutType: "list",
        headerStyle: "minimal",
        cardShape: "rounded-3xl",
        ctaStyle: "full-width",
        showPhoneBeforePlans: false,
        showWifiIcon: true,
        pageBg: "min-h-screen bg-[#e6e9f0]",
        cardClass: "bg-[#e6e9f0] rounded-3xl shadow-[10px_10px_20px_#c2c8d6,-10px_-10px_20px_#ffffff]",
        headerBg: "bg-[#e6e9f0]",
        headerText: "text-slate-800",
        headerSub: "text-slate-500",
        annBg: "bg-[#e6e9f0] shadow-[inset_3px_3px_6px_#c2c8d6,inset_-3px_-3px_6px_#ffffff]",
        annText: "text-slate-600",
        annIcon: "text-slate-500",
        planSelectedBorder: "border-transparent",
        planSelectedBg: "bg-[#e6e9f0] shadow-[inset_4px_4px_8px_#c2c8d6,inset_-4px_-4px_8px_#ffffff]",
        planBorder: "border-transparent",
        planBg: "bg-[#e6e9f0] shadow-[6px_6px_12px_#c2c8d6,-6px_-6px_12px_#ffffff]",
        planTitle: "text-slate-800",
        planSub: "text-slate-500",
        planPrice: "text-slate-700",
        planPopularBg: "bg-[#e6e9f0] shadow-[inset_2px_2px_4px_#c2c8d6,inset_-2px_-2px_4px_#ffffff]",
        planPopularText: "text-slate-600",
        inputBorder: "border-transparent",
        inputBg: "bg-[#e6e9f0] shadow-[inset_3px_3px_6px_#c2c8d6,inset_-3px_-3px_6px_#ffffff]",
        inputText: "text-slate-700",
        inputPlaceholder: "placeholder:text-slate-400",
        ctaBg: "bg-[#e6e9f0] shadow-[6px_6px_12px_#c2c8d6,-6px_-6px_12px_#ffffff] hover:shadow-[3px_3px_6px_#c2c8d6,-3px_-3px_6px_#ffffff] active:shadow-[inset_3px_3px_6px_#c2c8d6,inset_-3px_-3px_6px_#ffffff]",
        ctaText: "text-slate-700 font-bold",
        ctaHover: "",
        bodyText: "text-slate-600",
        mutedText: "text-slate-400",
        footerText: "text-slate-400",
        errorBg: "bg-[#e6e9f0] shadow-[inset_3px_3px_6px_#e0b8b8,inset_-3px_-3px_6px_#ffffff]",
        errorText: "text-red-500",
        successBg: "bg-[#e6e9f0] shadow-[inset_3px_3px_6px_#c2c8d6,inset_-3px_-3px_6px_#ffffff]",
        successPageBg: "min-h-screen bg-[#e6e9f0]",
      }
    case 14: // Brutalist Sun - Neo brutalist poster style
      return {
        layoutType: "grid",
        headerStyle: "left-aligned",
        cardShape: "rounded-none",
        ctaStyle: "full-width",
        showPhoneBeforePlans: true,
        showWifiIcon: true,
        pageBg: "min-h-screen bg-[#f8e637]",
        cardClass: "bg-[#fff7d1] border-4 border-black rounded-none shadow-[12px_12px_0_#111]",
        headerBg: "bg-black border-b-4 border-black",
        headerText: "text-[#f8e637]",
        headerSub: "text-white",
        annBg: "bg-white border-4 border-black shadow-[5px_5px_0_#111]",
        annText: "text-black",
        annIcon: "text-black",
        planSelectedBorder: "border-black",
        planSelectedBg: "bg-[#f43f5e] shadow-[5px_5px_0_#111]",
        planBorder: "border-black",
        planBg: "bg-white shadow-[4px_4px_0_#111]",
        planTitle: "text-black",
        planSub: "text-black/70",
        planPrice: "text-black",
        planPopularBg: "bg-black",
        planPopularText: "text-[#f8e637]",
        inputBorder: "border-black border-4",
        inputBg: "bg-white",
        inputText: "text-black",
        inputPlaceholder: "placeholder:text-black/40",
        ctaBg: "bg-black hover:bg-black",
        ctaText: "text-[#f8e637] font-extrabold",
        ctaHover: "hover:shadow-[6px_6px_0_#f43f5e]",
        bodyText: "text-black",
        mutedText: "text-black/60",
        footerText: "text-black/50",
        errorBg: "bg-white border-4 border-red-600",
        errorText: "text-red-700",
        successBg: "bg-[#ccff00] border-4 border-black",
        successPageBg: "min-h-screen bg-[#f8e637]",
      }
    case 15: // Brutalist Ink - Monochrome high contrast
      return {
        layoutType: "featured",
        headerStyle: "minimal",
        cardShape: "rounded-none",
        ctaStyle: "full-width",
        showPhoneBeforePlans: true,
        showWifiIcon: false,
        pageBg: "min-h-screen bg-white",
        cardClass: "bg-white border-4 border-black rounded-none shadow-[12px_12px_0_#f43f5e]",
        headerBg: "bg-white border-b-4 border-black",
        headerText: "text-black",
        headerSub: "text-black/60",
        annBg: "bg-[#ccff00] border-4 border-black shadow-[5px_5px_0_#111]",
        annText: "text-black",
        annIcon: "text-black",
        planSelectedBorder: "border-black",
        planSelectedBg: "bg-black shadow-[5px_5px_0_#ccff00]",
        planBorder: "border-black",
        planBg: "bg-white shadow-[4px_4px_0_#111]",
        planTitle: "text-black",
        planSub: "text-black/60",
        planPrice: "text-[#f43f5e]",
        planPopularBg: "bg-[#f43f5e]",
        planPopularText: "text-white",
        inputBorder: "border-black border-4",
        inputBg: "bg-white",
        inputText: "text-black",
        inputPlaceholder: "placeholder:text-black/40",
        ctaBg: "bg-[#f43f5e] hover:bg-[#e11d48]",
        ctaText: "text-white font-extrabold",
        ctaHover: "hover:shadow-[6px_6px_0_#111]",
        bodyText: "text-black",
        mutedText: "text-black/60",
        footerText: "text-black/50",
        errorBg: "bg-white border-4 border-red-600",
        errorText: "text-red-700",
        successBg: "bg-[#ccff00] border-4 border-black",
        successPageBg: "min-h-screen bg-white",
      }
    case 16: // Cyber Orchid - Retro cyberpunk glow
      return {
        layoutType: "grid",
        headerStyle: "large-hero",
        cardShape: "rounded-2xl",
        ctaStyle: "full-width",
        showPhoneBeforePlans: false,
        showWifiIcon: true,
        pageBg: "min-h-screen bg-gradient-to-br from-[#12071f] via-[#27105c] to-[#02121f]",
        cardClass: "bg-[#12071f]/95 border border-cyan-300/50 rounded-2xl shadow-2xl shadow-cyan-500/20",
        headerBg: "bg-gradient-to-r from-fuchsia-600/80 to-cyan-500/70 border-b border-cyan-300/40",
        headerText: "text-white",
        headerSub: "text-cyan-100",
        annBg: "bg-fuchsia-950/40 border border-fuchsia-400/40",
        annText: "text-fuchsia-100",
        annIcon: "text-fuchsia-300",
        planSelectedBorder: "border-cyan-300",
        planSelectedBg: "bg-cyan-400/10 shadow-[0_0_18px_rgba(34,211,238,0.25)]",
        planBorder: "border-fuchsia-400/30",
        planBg: "bg-white/5",
        planTitle: "text-white",
        planSub: "text-cyan-100/70",
        planPrice: "text-cyan-300",
        planPopularBg: "bg-fuchsia-500",
        planPopularText: "text-white",
        inputBorder: "border-cyan-300/40",
        inputBg: "bg-[#090414]",
        inputText: "text-cyan-50",
        inputPlaceholder: "placeholder:text-cyan-200/35",
        ctaBg: "bg-gradient-to-r from-fuchsia-500 to-cyan-400 hover:from-fuchsia-400 hover:to-cyan-300",
        ctaText: "text-[#090414] font-extrabold",
        ctaHover: "hover:shadow-fuchsia-500/30",
        bodyText: "text-cyan-50",
        mutedText: "text-cyan-100/60",
        footerText: "text-cyan-200/40",
        errorBg: "bg-red-950/50 border-red-500/40",
        errorText: "text-red-200",
        successBg: "bg-cyan-400/10 border-cyan-300/40",
        successPageBg: "min-h-screen bg-gradient-to-br from-[#12071f] via-[#27105c] to-[#02121f]",
      }
    case 17: // Retro Terminal - Cyber terminal command-center
      return {
        layoutType: "list",
        headerStyle: "left-aligned",
        cardShape: "rounded-lg",
        ctaStyle: "full-width",
        showPhoneBeforePlans: true,
        showWifiIcon: true,
        pageBg: "min-h-screen bg-[#02130a]",
        cardClass: "bg-[#031f10] border border-lime-400/60 rounded-lg shadow-2xl shadow-lime-500/10",
        headerBg: "bg-[#052e16] border-b border-lime-400/50",
        headerText: "text-lime-200",
        headerSub: "text-lime-400/70",
        annBg: "bg-lime-400/10 border border-lime-400/40",
        annText: "text-lime-100",
        annIcon: "text-lime-300",
        planSelectedBorder: "border-lime-300",
        planSelectedBg: "bg-lime-400/15 shadow-[0_0_18px_rgba(132,204,22,0.25)]",
        planBorder: "border-lime-400/30",
        planBg: "bg-black/20",
        planTitle: "text-lime-100",
        planSub: "text-lime-500/80",
        planPrice: "text-lime-300",
        planPopularBg: "bg-lime-300",
        planPopularText: "text-[#02130a]",
        inputBorder: "border-lime-400/40",
        inputBg: "bg-black/40",
        inputText: "text-lime-100",
        inputPlaceholder: "placeholder:text-lime-500/45",
        ctaBg: "bg-lime-300 hover:bg-lime-200",
        ctaText: "text-[#02130a] font-extrabold",
        ctaHover: "hover:shadow-lime-400/25",
        bodyText: "text-lime-100",
        mutedText: "text-lime-500/70",
        footerText: "text-lime-500/40",
        errorBg: "bg-red-950/40 border-red-500/40",
        errorText: "text-red-200",
        successBg: "bg-lime-400/10 border-lime-400/40",
        successPageBg: "min-h-screen bg-[#02130a]",
      }
    default: // Classic (1) - Grid Layout (Professional, ISP standard)
      return {
        layoutType: "grid",
        headerStyle: "centered",
        cardShape: "rounded-2xl",
        ctaStyle: "full-width",
        showPhoneBeforePlans: false,
        showWifiIcon: true,
        pageBg: "min-h-screen bg-gradient-to-br from-blue-50 to-indigo-100",
        cardClass: "bg-white rounded-2xl shadow-xl",
        headerBg: "bg-blue-600",
        headerText: "text-white",
        headerSub: "text-white/80",
        annBg: "bg-blue-50 border border-blue-200",
        annText: "text-blue-700",
        annIcon: "text-blue-500",
        planSelectedBorder: "border-blue-500",
        planSelectedBg: "bg-blue-50",
        planBorder: "border-gray-200",
        planBg: "bg-white",
        planTitle: "text-gray-900",
        planSub: "text-gray-500",
        planPrice: "text-blue-600",
        planPopularBg: "bg-blue-500",
        planPopularText: "text-white",
        inputBorder: "border-gray-300",
        inputBg: "bg-white",
        inputText: "text-gray-900",
        inputPlaceholder: "placeholder:text-gray-400",
        ctaBg: "bg-blue-600 hover:bg-blue-700",
        ctaText: "text-white",
        ctaHover: "",
        bodyText: "text-gray-700",
        mutedText: "text-gray-500",
        footerText: "text-gray-400",
        errorBg: "bg-red-50 border-red-200",
        errorText: "text-red-700",
        successBg: "bg-green-50",
        successPageBg: "min-h-screen bg-gradient-to-br from-green-50 to-emerald-100",
      }
  }
}
