import type { BlogPost } from "./blog-data"

export const businessGrowthGuides: BlogPost[] = [
  {
    slug: "advertise-internet-service-social-media-local-marketing",
    title: "How to Advertise Your Internet Service Using Social Media, Local Marketing and Referrals",
    excerpt: "A practical marketing guide for WISPs and local ISPs that want more enquiries from estates, shops, apartments and small businesses.",
    coverGradient: "from-emerald-600 to-sky-700",
    coverImage: "https://images.unsplash.com/photo-1557838923-2985c318be48?auto=format&fit=crop&w=1400&q=75",
    coverImageAlt: "Marketing team planning a local campaign on a desk",
    category: "ISP Growth",
    categoryColor: "emerald",
    readTime: 6,
    publishedAt: "2026-09-18",
    updatedAt: "2026-09-18",
    author: { name: "Netily Editorial Team", role: "ISP Growth", initials: "NT", avatarBg: "bg-emerald-600" },
    tags: ["ISP Marketing", "Social Media", "Local Marketing", "Referrals", "WISP Growth"],
    metaTitle: "How to Advertise Your Internet Service | ISP Marketing Guide",
    metaDescription: "Learn practical social media, estate marketing, referral and local sales ideas for WISPs and ISPs that want more qualified internet subscribers.",
    keywords: [
      "how to advertise internet service",
      "ISP marketing ideas",
      "WISP marketing strategy",
      "internet service provider advertising",
      "estate WiFi marketing",
      "Facebook ads for ISP",
      "WhatsApp marketing for WISP",
      "local ISP lead generation",
      "internet provider referrals",
      "ISP billing software Kenya",
      "Centipid alternative",
      "ISPMAN alternative",
      "WISPMAN alternative",
      "Jasiyo alternative",
    ],
    spatialCoverage: ["Kenya", "Uganda", "Tanzania", "South Africa"],
    toc: [
      { id: "know-your-area", text: "Know the area you serve" },
      { id: "make-offer-clear", text: "Make the offer clear" },
      { id: "social-media", text: "Use social media well" },
      { id: "local-marketing", text: "Win local trust" },
      { id: "referrals", text: "Turn customers into promoters" },
      { id: "measure", text: "Track what works" },
      { id: "faq", text: "Common questions" },
    ],
    content: [
      { type: "p", html: "Advertising an internet service works best when the message is local, specific and easy to act on. People rarely wake up looking for a random ISP. They look for reliable WiFi in their estate, a better connection for their shop, or a provider who answers when something breaks." },
      { type: "p", html: "For a WISP or neighbourhood ISP, the strongest campaigns combine social media, local visibility, referrals and fast follow-up. The goal is not only to get more views. It is to get qualified enquiries from people inside the coverage area who understand the price, installation process and support promise." },
      { type: "h2", id: "know-your-area", text: "Start with the area you can serve well" },
      { type: "p", html: "Map your real coverage before spending money on ads. List estates, apartment blocks, business streets, schools, clinics and nearby shops where installation is realistic. Use the names people already use locally: the estate name, stage, road, building or landmark." },
      { type: "ul", items: ["Create one short message for home users, one for businesses and one for landlords or caretakers.", "Mention actual service areas instead of only saying 'available nationwide'.", "Keep a simple installation checklist ready for every lead source.", "Record why a lead could not be installed so the next campaign becomes sharper."] },
      { type: "h2", id: "make-offer-clear", text: "Make the internet offer easy to understand" },
      { type: "p", html: "A good ISP advert answers the customer's first questions quickly: how much, how fast, where available, installation cost, support contact and how to join. Avoid technical copy in the first line. Lead with the everyday result: stable home WiFi, fast business internet, estate hotspot access or fibre for apartments." },
      { type: "table", headers: ["Audience", "Message angle", "Best channel"], rows: [
        ["Home users", "Stable WiFi for streaming, work and school", "Facebook, TikTok, WhatsApp groups, estate posters"],
        ["Small businesses", "Reliable internet with support and receipts", "Google Business Profile, direct visits, referrals"],
        ["Landlords and caretakers", "Managed WiFi for tenants with simple payments", "In-person visits, printed proposal, WhatsApp follow-up"],
        ["Students and hotspots", "Affordable daily, weekly or monthly packages", "Posters, social stories, local influencers"],
      ] },
      { type: "h2", id: "social-media", text: "Use social media to create demand and answer objections" },
      { type: "p", html: "Post content that proves the service exists in the customer's area. Show new installations, coverage updates, package reminders, support hours and short answers to common questions. Keep customer privacy in mind: avoid exposing house numbers, phone numbers, router credentials or private conversations." },
      { type: "ol", items: ["Create location-specific posts for each estate or town you serve.", "Use short videos to show installation, speed tests and customer onboarding without overpromising speeds.", "Run small paid campaigns around a single coverage area instead of boosting every post broadly.", "Reply quickly to comments and move serious enquiries to a lead form or WhatsApp with a clear next step.", "Retarget people who engaged with package posts using a simple installation offer."] },
      { type: "callout", variant: "tip", title: "Keep the promise measurable", text: "Instead of saying 'the fastest internet everywhere', say where you install, what packages are available and how quickly your team follows up." },
      { type: "h2", id: "local-marketing", text: "Win local trust offline" },
      { type: "p", html: "Local marketing still matters because internet is a household decision. Posters near shops, agent referrals, caretaker relationships and estate demos can outperform broad online ads when the coverage area is tight. Give every offline touchpoint a trackable phone number, QR code or short link." },
      { type: "ul", items: ["Place posters where residents already look for notices, with permission from the property owner.", "Offer caretakers and local agents a clear referral process and payout rule.", "Run a weekend demo at a shop, church compound, apartment gate or business cluster.", "Prepare a one-page proposal for landlords showing pricing, support process and payment options.", "Follow up every enquiry the same day while the customer still remembers the advert."] },
      { type: "h2", id: "referrals", text: "Turn happy customers into promoters" },
      { type: "p", html: "A referral programme works when the reward is simple and the customer knows exactly how to share it. Give existing customers a referral link or code, then record the lead source when someone submits the contact form. Reward after installation or first successful payment, depending on your policy." },
      { type: "p", html: "Keep the referral language human: 'Share this link with a neighbour. When they connect and pay, you receive your reward.' Avoid complicated points systems until the basics are working." },
      { type: "h2", id: "measure", text: "Track leads from advert to installation" },
      { type: "p", html: "Marketing becomes easier when every lead has a source. Track the channel, estate, package interest, assigned salesperson, follow-up status and final outcome. A billing and customer system such as <a href=\"/solutions/isp-billing-software-kenya\">Netily ISP billing software</a> helps connect marketing enquiries to real customers, payments and renewals." },
      { type: "ul", items: ["Cost per qualified lead", "Lead-to-installation conversion rate", "Average time to first response", "Best estates by active customer growth", "Churn and support issues by campaign source"] },
      { type: "h2", id: "faq", text: "Common questions about ISP advertising" },
      { type: "h3", text: "Should an ISP advertise packages or coverage first?" },
      { type: "p", html: "Lead with coverage when the area is specific, then show packages. A customer first needs to know whether you can install where they live or work." },
      { type: "h3", text: "Do social media ads work for WISPs?" },
      { type: "p", html: "Yes, when the targeting is local and the offer is clear. Broad ads can waste money if they reach people outside your coverage area." },
      { type: "p", html: "For more operational growth ideas, read the <a href=\"/blog/isp-growth-retention-cashflow-playbook\">ISP growth, retention and cashflow playbook</a> and the <a href=\"/blog/self-care-captive-portal-isp-renewals\">self-care portal guide</a>." },
      { type: "cta" },
    ],
  },
  {
    slug: "isp-growth-retention-cashflow-playbook",
    title: "The ISP Growth, Retention and Cashflow Playbook for Small and Growing Providers",
    excerpt: "Simple operating habits that help ISPs grow without losing control of support, renewals, cashflow and customer trust.",
    coverGradient: "from-blue-600 to-emerald-700",
    coverImage: "https://images.unsplash.com/photo-1552664730-d307ca884978?auto=format&fit=crop&w=1400&q=75",
    coverImageAlt: "Business team reviewing growth plans around a table",
    category: "ISP Business",
    categoryColor: "blue",
    readTime: 6,
    publishedAt: "2026-09-18",
    updatedAt: "2026-09-18",
    author: { name: "Netily Editorial Team", role: "ISP Growth", initials: "NT", avatarBg: "bg-blue-600" },
    tags: ["ISP Growth", "Retention", "Cashflow", "Customer Success", "Operations"],
    metaTitle: "ISP Growth, Retention and Cashflow Playbook | Netily",
    metaDescription: "A practical playbook for small and growing ISPs: improve retention, renewals, cashflow, support discipline and profitable customer growth.",
    keywords: [
      "how to grow an ISP business",
      "WISP business growth",
      "ISP customer retention",
      "ISP cashflow management",
      "internet provider churn reduction",
      "ISP renewal automation",
      "ISP business software",
      "Netily ISP management",
      "Internetily ISP software",
      "Splynx alternative",
      "Centipid alternative",
      "ISPMAN alternative",
      "WISPMAN alternative",
      "Jasiyo alternative",
    ],
    spatialCoverage: ["Kenya", "Uganda", "Tanzania", "South Africa"],
    toc: [
      { id: "growth-quality", text: "Grow with quality" },
      { id: "retention", text: "Reduce avoidable churn" },
      { id: "cashflow", text: "Protect cashflow" },
      { id: "support", text: "Make support measurable" },
      { id: "expansion", text: "Choose the next area" },
      { id: "faq", text: "Common questions" },
    ],
    content: [
      { type: "p", html: "An ISP grows well when new installations, renewals, support and collections move together. If marketing brings many customers but installation records are weak, the team loses control. If payments are collected but support is slow, churn rises. Growth is not only more customers; it is more reliable customers on a system the team can run." },
      { type: "h2", id: "growth-quality", text: "Grow with quality, not just signups" },
      { type: "p", html: "Before pushing a new campaign, define what a good customer looks like for your network. A good customer is inside a serviceable area, chooses a package they can renew, understands the installation terms and receives support through a channel your team can manage." },
      { type: "ul", items: ["Confirm the coverage area before accepting installation money.", "Keep installation photos, router details and customer contacts in one record.", "Give every new customer a simple renewal path from day one.", "Avoid selling speeds that the backhaul and last-mile design cannot sustain.", "Review the first seven days after installation because early issues create long-term distrust."] },
      { type: "h2", id: "retention", text: "Reduce avoidable churn before chasing more leads" },
      { type: "p", html: "Many ISPs lose money quietly through avoidable churn: late reminders, slow reconnection, repeated faults, unclear package rules and weak support handovers. Fixing these problems often grows revenue faster than increasing ad spend." },
      { type: "table", headers: ["Churn reason", "Early warning", "Useful response"], rows: [
        ["Late renewal", "Customer expires often but returns after reminders", "Send earlier reminders and offer easy renewal"],
        ["Poor support", "Repeated unresolved complaints", "Assign owner, track resolution time and follow up"],
        ["Wrong package", "Heavy usage complaints on low package", "Suggest a better package with clear value"],
        ["Coverage problem", "Frequent faults in one area", "Audit AP, fibre route or backhaul before more sales"],
      ] },
      { type: "h2", id: "cashflow", text: "Protect cashflow with clean billing habits" },
      { type: "p", html: "Cashflow improves when invoices, payments and access rules are predictable. Use one source of truth for subscription dates. Separate customer payments from business expenses. Reconcile provider statements with billing records often, especially for M-Pesa, bank and manual payments." },
      { type: "ol", items: ["Send renewal reminders before expiry, not only after disconnection.", "Record adjustments with a reason and approver.", "Avoid keeping paid customers stuck behind a payment guard after confirmation.", "Review failed and pending payments daily until automation is reliable.", "Track active, expired, inactive and trial customers separately."] },
      { type: "p", html: "See the <a href=\"/blog/automate-wisp-billing-mpesa-auto-disconnect\">M-Pesa billing automation guide</a> for payment-to-access workflow ideas." },
      { type: "h2", id: "support", text: "Make support visible and measurable" },
      { type: "p", html: "Support should show patterns, not only individual complaints. Tag issues by type: payment, router offline, slow speed, installation, account change, outage, billing dispute or equipment replacement. This helps the owner see whether the problem is sales, network capacity, process or staff discipline." },
      { type: "ul", items: ["Track who created or edited a customer record.", "Record plan activations and manual payment actions.", "Measure time from complaint to first response and final resolution.", "Keep staff permissions aligned to their actual responsibilities.", "Use customer notes to avoid asking the same questions repeatedly."] },
      { type: "h2", id: "expansion", text: "Choose the next area using evidence" },
      { type: "p", html: "Before expanding, compare demand, installation cost, competitor strength, support distance, power reliability and collection behaviour. A nearby estate with many referrals may be better than a far location with cheap ad leads. If one AP or fibre route is already strained, improve capacity before adding more customers on top of it." },
      { type: "callout", variant: "info", title: "One useful weekly meeting", text: "Review new leads, new installs, failed installs, churn, overdue accounts, support tickets and network incidents. Keep it short, but make every number owned by someone." },
      { type: "h2", id: "faq", text: "Common questions about growing an ISP" },
      { type: "h3", text: "What is the easiest way to improve ISP revenue?" },
      { type: "p", html: "Start with renewal discipline. Better reminders, reliable payment confirmation and faster reconnection can recover money that is already close to the business." },
      { type: "h3", text: "Should a small ISP use spreadsheets first?" },
      { type: "p", html: "Spreadsheets can work briefly, but they become risky when payments, routers, staff actions and support history need to agree. Move to a proper system before the team starts making decisions from different records." },
      { type: "p", html: "Explore <a href=\"/solutions/mikrotik-billing-software\">MikroTik ISP billing workflows</a> and the <a href=\"/blog/advertise-internet-service-social-media-local-marketing\">ISP marketing guide</a> to connect sales with operations." },
      { type: "cta" },
    ],
  },
  {
    slug: "isp-customer-experience-support-automation-guide",
    title: "How ISPs Can Improve Customer Experience with Support Automation, Portals and Clear Communication",
    excerpt: "A practical guide to reducing confusion, improving renewals and giving subscribers better support without overwhelming the team.",
    coverGradient: "from-purple-600 to-orange-600",
    coverImage: "https://images.unsplash.com/photo-1553877522-43269d4ea984?auto=format&fit=crop&w=1400&q=75",
    coverImageAlt: "Support team working together in a modern office",
    category: "Customer Experience",
    categoryColor: "purple",
    readTime: 6,
    publishedAt: "2026-09-18",
    updatedAt: "2026-09-18",
    author: { name: "Netily Editorial Team", role: "ISP Operations", initials: "NT", avatarBg: "bg-purple-600" },
    tags: ["Customer Experience", "Support Automation", "ISP Portal", "Renewals", "Operations"],
    metaTitle: "ISP Customer Experience & Support Automation Guide | Netily",
    metaDescription: "Improve ISP customer experience with clear billing communication, self-care portals, support workflows, outage updates and renewal automation.",
    keywords: [
      "ISP customer experience",
      "ISP support automation",
      "internet provider customer portal",
      "reduce ISP support calls",
      "ISP outage communication",
      "ISP renewal reminders",
      "hotspot self care portal",
      "PPPoE customer portal",
      "ISP CRM Kenya",
      "WISP customer support",
      "Centipid alternative",
      "ISPMAN alternative",
      "WISPMAN alternative",
      "Jasiyo alternative",
    ],
    spatialCoverage: ["Kenya", "Uganda", "Tanzania", "South Africa"],
    toc: [
      { id: "clear-status", text: "Show clear account status" },
      { id: "support-workflow", text: "Structure support work" },
      { id: "outage-updates", text: "Communicate outages well" },
      { id: "automation", text: "Automate the right moments" },
      { id: "feedback", text: "Use feedback wisely" },
      { id: "faq", text: "Common questions" },
    ],
    content: [
      { type: "p", html: "Most ISP customer experience problems come from uncertainty. The customer does not know whether their account is active, whether payment was received, whether an outage is known, or who is handling the complaint. A good system reduces that uncertainty before it becomes anger." },
      { type: "h2", id: "clear-status", text: "Show customers a clear account status" },
      { type: "p", html: "A customer portal should show the package, expiry date, renewal amount, payment status and support contact in plain language. Use separate messages for payment pending, payment received, reconnecting service, active service and expired service. These are not the same experience." },
      { type: "ul", items: ["Let customers see their current package and renewal date.", "Show payment attempts with useful status instead of a silent spinner.", "Give expired customers a direct renewal path.", "Keep invoices and receipts easy to find.", "Use simple language that a non-technical household can understand."] },
      { type: "h2", id: "support-workflow", text: "Structure support work so issues do not disappear" },
      { type: "p", html: "Support should move through clear stages: new, assigned, waiting for customer, waiting for technician, resolved and closed. Each issue needs an owner, a customer, a category and a last update. For technical teams, this is basic discipline. For customers, it feels like the company knows what it is doing." },
      { type: "table", headers: ["Issue type", "Useful detail to capture", "Good next step"], rows: [
        ["Payment issue", "Reference, amount, payer phone, time", "Check payment record and activation status"],
        ["Slow speed", "Package, device, time, location", "Check session, signal or router load"],
        ["No internet", "Customer status, router/AP state, outage area", "Verify account then network path"],
        ["Installation", "Address, estate, phone, package", "Assign technician and appointment window"],
      ] },
      { type: "h2", id: "outage-updates", text: "Communicate outages before customers flood support" },
      { type: "p", html: "When an area outage happens, silence creates repeated calls. Send a short update to affected customers when the issue is confirmed, then another when service is restored. Avoid blaming suppliers in vague language. Say the area affected, what customers may notice and when the next update will come." },
      { type: "callout", variant: "tip", title: "Keep outage messages short", text: "Customers want to know whether you know about the issue, whether they need to do anything and when they will hear from you again." },
      { type: "h2", id: "automation", text: "Automate the moments that repeat every day" },
      { type: "p", html: "Automation should help customers at predictable moments: welcome after installation, renewal reminders, payment confirmation, reconnection, outage update, support ticket receipt and resolved ticket follow-up. Keep the message direct and useful. Do not send many alerts that repeat the same thing." },
      { type: "ol", items: ["Send renewal reminders before expiry and once after expiry.", "Confirm payment only after the provider or manual receipt is accepted.", "Tell the customer when reconnection is in progress.", "Escalate a payment that is confirmed but not activated after a set time.", "Ask for feedback after resolution, not while the customer is still waiting."] },
      { type: "p", html: "The <a href=\"/blog/self-care-captive-portal-isp-renewals\">self-care captive portal guide</a> explains how to turn these states into a smoother renewal journey." },
      { type: "h2", id: "feedback", text: "Use feedback to improve the business, not only support" },
      { type: "p", html: "Customer complaints are business data. A repeated payment complaint may reveal callback problems. A repeated speed complaint may reveal oversold capacity. A repeated installation complaint may reveal poor scheduling. Review feedback weekly and connect it to network, billing and staffing decisions." },
      { type: "ul", items: ["Top support categories this week", "Customers with repeated complaints", "Payments confirmed but not activated quickly", "Areas with recurring faults", "Staff actions that need approval or audit"] },
      { type: "h2", id: "faq", text: "Common questions about ISP customer experience" },
      { type: "h3", text: "What should an ISP automate first?" },
      { type: "p", html: "Start with renewal reminders, payment confirmation and reconnection status. These are high-volume moments where customers quickly lose trust if the message is unclear." },
      { type: "h3", text: "Can better support reduce churn?" },
      { type: "p", html: "Yes, especially when the customer can see progress and does not have to repeat the same details. Support will not fix a weak network, but it can make the business feel organised and accountable." },
      { type: "p", html: "Explore <a href=\"/solutions/hotspot-billing-software-kenya\">hotspot billing software</a> and <a href=\"/solutions/mpesa-isp-billing\">M-Pesa ISP billing</a> to connect customer communication with billing and access." },
      { type: "cta" },
    ],
  },
]
