import type { BlogPost } from "./blog-data"

const editorialAuthor = {
  name: "Netily Editorial Team",
  role: "ISP Network Operations",
  initials: "NT",
  avatarBg: "bg-blue-600",
}

export const networkInfrastructureGuides: BlogPost[] = [
  {
    slug: "tr069-cpe-management-for-growing-isps",
    title: "TR-069 for Growing ISPs: How to Manage Customer Routers Without Losing Your Weekends",
    excerpt:
      "A simple guide to TR-069, ACS setup, customer router visibility and how Internetily helps tenants keep CPE management tidy as they scale.",
    coverGradient: "from-blue-600 to-cyan-700",
    coverImage: "https://images.unsplash.com/photo-1558494949-ef010cbdcc31?auto=format&fit=crop&w=1400&q=75",
    coverImageAlt: "Network equipment and patch cables in a data centre rack",
    category: "Network Operations",
    categoryColor: "blue",
    readTime: 6,
    publishedAt: "2026-09-29",
    updatedAt: "2026-09-29",
    author: editorialAuthor,
    tags: ["TR-069", "ACS", "CPE Management", "ISP Operations", "Internetily"],
    metaTitle: "TR-069 CPE Management for Growing ISPs | Internetily",
    metaDescription:
      "Learn how ISPs can use TR-069 and ACS workflows to manage customer routers, reduce support visits and scale CPE operations with Internetily.",
    keywords: [
      "TR-069 ISP management",
      "ACS for ISP",
      "CPE management software",
      "customer router management",
      "remote router provisioning",
      "ISP support automation",
      "Internetily TR-069",
      "Netily ISP software",
      "WISP operations Kenya",
      "ISP management Uganda",
      "ISP software Tanzania",
      "ISP software South Africa",
    ],
    spatialCoverage: ["Kenya", "Uganda", "Tanzania", "South Africa"],
    toc: [
      { id: "why-tr069", text: "Why TR-069 matters" },
      { id: "setup-basics", text: "Set up the basics" },
      { id: "tenant-workflow", text: "Make it useful for tenants" },
      { id: "scale", text: "Scale without chaos" },
      { id: "internetily", text: "Where Internetily fits" },
    ],
    content: [
      { type: "p", html: "TR-069 is one of those ISP tools that sounds dry until the first Saturday when a customer router needs a tiny setting changed across town. Suddenly, remote customer equipment management feels less like a luxury and more like peace of mind." },
      { type: "p", html: "For a growing ISP, the goal is not to click into every router all day. The goal is to know which customer has which router, which settings are expected, what changed, and whether the device can be supported without sending a technician for every small issue." },
      { type: "h2", id: "why-tr069", text: "Why TR-069 matters" },
      { type: "p", html: "TR-069 lets compatible customer routers talk to an Auto Configuration Server, commonly called an ACS. That gives the ISP a controlled way to provision, inspect and troubleshoot supported customer equipment. It is especially useful when many households use similar routers and your team wants a standard setup instead of one-off fixes." },
      { type: "ul", items: ["Push standard WiFi names, support settings or WAN profiles where supported.", "See device identity, firmware and basic health without asking the customer to read small labels.", "Reduce repeat field visits for simple customer-router changes.", "Keep a cleaner record of router ownership, replacement and support history."] },
      { type: "h2", id: "setup-basics", text: "Set up the basics before adding many devices" },
      { type: "p", html: "Start with a small test group. Confirm the router model, firmware, ACS URL, authentication method and the exact parameters your team needs. A router saying it supports TR-069 does not mean every useful value is exposed in the same way." },
      { type: "ol", items: ["Pick two or three approved router models for new installations.", "Test each model with your ACS before buying in bulk.", "Document the default profile your technicians should apply.", "Decide who is allowed to push changes and who can only view diagnostics.", "Keep a rollback path for any profile change that affects many customers."] },
      { type: "h2", id: "tenant-workflow", text: "Make the workflow useful for tenants" },
      { type: "p", html: "Inside an ISP management system, TR-069 is most useful when it is tied to the customer record. A support agent should not be guessing which router belongs to which account. The customer, service plan, router, payment state and support notes should all tell the same story." },
      { type: "table", headers: ["Tenant need", "Good practice"], rows: [
        ["New customer setup", "Attach the CPE record during installation, not later from memory."],
        ["Support call", "Open the customer record first, then inspect the linked device."],
        ["Router swap", "Retire the old device, attach the new one and keep the history."],
        ["Staff control", "Limit profile changes to trained users and log the action."],
      ] },
      { type: "h2", id: "scale", text: "Scale without turning support into guesswork" },
      { type: "p", html: "As coverage grows from one estate to several towns, standardisation becomes the friendly boss. Use naming rules, approved device lists, installation checklists and clear escalation paths. A small ISP can survive on memory. A scaling ISP needs records that another technician can understand at 8 a.m. with no drama." },
      { type: "callout", variant: "tip", title: "Keep it boring on purpose", text: "The best CPE workflow is boring: known devices, known profiles, clear ownership and logs. Boring is what lets the business sleep." },
      { type: "h2", id: "internetily", text: "How Internetily helps" },
      { type: "p", html: "Internetily is built to keep billing, customers, routers, support and network operations in one working view. For TR-069-style operations, the practical value is the structure around the device: customer mapping, staff accountability, support context, and room to connect provisioning workflows as the ISP matures." },
      { type: "p", html: "Tenants can start with clean customer and router records, then grow into deeper device automation without losing the basics. That matters because the best automation still needs accurate people, places, packages and devices behind it." },
      { type: "cta" },
    ],
  },
  {
    slug: "olt-management-ftth-isps-internetily-guide",
    title: "OLT Management for FTTH ISPs: Keep Fibre Customers Connected Without Spreadsheet Gymnastics",
    excerpt:
      "A human guide to OLT management, ONU records, subscriber mapping and how Internetily supports fibre ISPs as they grow from a few lines to many estates.",
    coverGradient: "from-emerald-600 to-blue-700",
    coverImage: "https://images.unsplash.com/photo-1516321318423-f06f85e504b3?auto=format&fit=crop&w=1400&q=75",
    coverImageAlt: "Engineer reviewing fibre network records on a laptop",
    category: "FTTH Operations",
    categoryColor: "emerald",
    readTime: 6,
    publishedAt: "2026-09-29",
    updatedAt: "2026-09-29",
    author: editorialAuthor,
    tags: ["OLT Management", "FTTH", "ONU", "Fibre ISP", "Internetily"],
    metaTitle: "OLT Management for FTTH ISPs | Internetily Guide",
    metaDescription:
      "Learn OLT management best practices for FTTH ISPs: ONU mapping, subscriber records, provisioning discipline, support workflows and Internetily scaling tools.",
    keywords: [
      "OLT management software",
      "FTTH ISP management",
      "ONU provisioning",
      "fibre ISP billing software",
      "SmartOLT alternative workflow",
      "Huawei OLT management",
      "ZTE OLT management",
      "Internetily FTTH",
      "Netily fibre ISP software",
      "ISP OLT operations",
    ],
    spatialCoverage: ["Kenya", "Uganda", "Tanzania", "South Africa"],
    toc: [
      { id: "records", text: "Start with records" },
      { id: "provisioning", text: "Provision carefully" },
      { id: "support", text: "Support with context" },
      { id: "scale", text: "Scale fibre operations" },
      { id: "internetily", text: "Internetily's role" },
    ],
    content: [
      { type: "p", html: "OLT management is not just about logging into equipment. It is about knowing which customer lives behind which ONU, which port serves which area, which package should be active, and what changed when support says, 'this one was working yesterday.'" },
      { type: "p", html: "For fibre ISPs, a clean operational record is the difference between calm troubleshooting and everyone scrolling through chats looking for a serial number. The equipment matters, but the daily workflow around it matters just as much." },
      { type: "h2", id: "records", text: "Start with customer and ONU records" },
      { type: "p", html: "Every fibre customer should have a stable record that links the subscriber, location, package, ONU serial, OLT, port and installation notes. A customer's name alone is not enough. Names repeat. People move. Devices get replaced. Serial numbers and service records keep the truth steady." },
      { type: "ul", items: ["Capture the ONU serial during installation.", "Record the OLT, PON port, splitter area and customer location.", "Keep package, billing status and service state visible together.", "Store installation photos or notes where support can find them.", "Log device replacements instead of overwriting history with no explanation."] },
      { type: "h2", id: "provisioning", text: "Provision carefully, especially during growth" },
      { type: "p", html: "Good provisioning is repeatable. Use tested profiles, clear naming rules and approval for changes that affect many customers. If the team is using an OLT tool such as SmartOLT or direct vendor management, decide which system owns each action and avoid making the same change from three places." },
      { type: "table", headers: ["Area", "Best practice"], rows: [
        ["Profiles", "Use a small set of approved speed and service profiles."],
        ["Names", "Use naming that shows area, port or customer reference clearly."],
        ["Changes", "Log who changed a profile and why."],
        ["Rollback", "Keep a safe way to reverse bulk changes."],
      ] },
      { type: "h2", id: "support", text: "Support fibre customers with context" },
      { type: "p", html: "When a customer calls, the support team should see billing status, active package, device details and recent network notes before asking the customer to reboot for the fifth time. A paid customer with an offline ONU is a different problem from an expired account with a working line." },
      { type: "ol", items: ["Check whether the account is active and paid.", "Check whether the customer is affected by an area issue.", "Check ONU and OLT details.", "Review recent staff changes or support notes.", "Escalate with enough technical context for the field team."] },
      { type: "h2", id: "scale", text: "Scale fibre operations area by area" },
      { type: "p", html: "A fibre ISP can start small and still design for growth. Keep estates, buildings, roads and splitter zones organised from the beginning. When the network grows, those labels become the map your support, sales and field teams use every day." },
      { type: "callout", variant: "info", title: "The useful scaling question", text: "If your best technician is away, can another person find the customer, ONU and service history in under one minute?" },
      { type: "h2", id: "internetily", text: "How Internetily helps fibre tenants" },
      { type: "p", html: "Internetily helps fibre-focused tenants keep customer records, billing status, invoices, payments, support notes and network assets closer together. That gives the ISP a reliable operating layer around the OLT tools already in use." },
      { type: "p", html: "As the tenant grows, Internetily supports better staff controls, audit trails, renewal workflows and customer communication, so fibre operations do not depend on memory and scattered spreadsheets." },
      { type: "cta" },
    ],
  },
  {
    slug: "ap-mapping-for-wisps-and-estate-wifi",
    title: "AP Mapping for WISPs and Estate WiFi: See Coverage Before Customers Start Shouting",
    excerpt:
      "A practical AP mapping guide for WISPs, hotspot operators and estate WiFi teams that want cleaner coverage, faster support and scalable operations with Internetily.",
    coverGradient: "from-purple-600 to-orange-600",
    coverImage: "https://images.unsplash.com/photo-1581090464777-f3220bbe1b8b?auto=format&fit=crop&w=1400&q=75",
    coverImageAlt: "Technician planning wireless coverage on a tablet",
    category: "Wireless Operations",
    categoryColor: "purple",
    readTime: 6,
    publishedAt: "2026-09-29",
    updatedAt: "2026-09-29",
    author: editorialAuthor,
    tags: ["AP Mapping", "WISP", "Estate WiFi", "Hotspot", "Internetily"],
    metaTitle: "AP Mapping for WISPs and Estate WiFi | Internetily",
    metaDescription:
      "Plan AP mapping for WISPs and estate WiFi: coverage records, device health, tenant workflows, support triage and scalable wireless operations with Internetily.",
    keywords: [
      "AP mapping software",
      "WISP access point mapping",
      "estate WiFi management",
      "hotspot AP monitoring",
      "wireless ISP coverage mapping",
      "MikroTik AP management",
      "Internetily AP mapping",
      "Netily WISP software",
      "WiFi coverage planning Kenya",
      "estate internet provider software",
    ],
    spatialCoverage: ["Kenya", "Uganda", "Tanzania", "South Africa"],
    toc: [
      { id: "why-map", text: "Why map APs" },
      { id: "what-to-track", text: "What to track" },
      { id: "tenant-setup", text: "Set it up for tenants" },
      { id: "support", text: "Use it in support" },
      { id: "scale", text: "Scale the network" },
    ],
    content: [
      { type: "p", html: "AP mapping gives a wireless ISP a simple superpower: knowing where the access points are before a customer explains the network to you. It sounds obvious, but many growing operators still rely on memory, WhatsApp photos and that one technician who knows the roof by heart." },
      { type: "p", html: "A clean AP map helps the team see coverage areas, likely affected customers, device ownership and where to send a technician. For estate WiFi and hotspot operators, it also makes expansion less like guesswork and more like planning." },
      { type: "h2", id: "why-map", text: "Why AP mapping matters" },
      { type: "ul", items: ["Know which AP serves each estate, building, floor or hotspot zone.", "Troubleshoot area issues faster by grouping affected customers.", "Plan capacity upgrades before one AP becomes everyone's bad day.", "Make technician handovers easier when staff change.", "Support growth into new estates with better coverage records."] },
      { type: "h2", id: "what-to-track", text: "Track the details that support actually uses" },
      { type: "p", html: "A useful AP record does not need to be complicated. Start with the AP name, location, router, upstream link, model, IP address, mounting point, power source, expected coverage area and the customers or hotspot plans tied to that zone." },
      { type: "table", headers: ["Record", "Why it helps"], rows: [
        ["Location", "Technicians find the device faster."],
        ["Coverage area", "Support knows which customers may be affected."],
        ["Upstream link", "The team can tell whether the issue is AP, backhaul or router."],
        ["Power source", "Power failures stop being a mystery tour."],
        ["Customer zone", "Billing and support can speak the same language."],
      ] },
      { type: "h2", id: "tenant-setup", text: "Set up AP mapping tenant by tenant" },
      { type: "p", html: "Every tenant has a different ground reality. One serves apartments, another serves schools and shops, another serves a wide outdoor WISP zone. The mapping workflow should let each tenant use names that match their area while keeping the core fields consistent." },
      { type: "ol", items: ["Create location groups such as estate, building, school, tower or business street.", "Add each AP with a clear name that technicians recognise.", "Attach router and upstream details where available.", "Link customers, hotspot zones or service areas to the AP.", "Review the map after every installation, relocation or outage."] },
      { type: "h2", id: "support", text: "Use the AP map during support, not only during setup" },
      { type: "p", html: "When five customers from the same block complain, the support team should not treat them as five unrelated mysteries. AP mapping helps support ask better questions and escalate faster. It also helps owners see which parts of the network generate the most support pressure." },
      { type: "callout", variant: "tip", title: "Do not over-map on day one", text: "Start with AP name, location and coverage area. Add signal, capacity and topology details as the team actually starts using the map." },
      { type: "h2", id: "scale", text: "How Internetily helps AP-heavy tenants scale" },
      { type: "p", html: "Internetily is being shaped to give tenants better visibility across routers, hotspot operations, customers, billing and network assets. AP mapping fits naturally into that picture because it connects the physical network to the people paying for service." },
      { type: "p", html: "That means a tenant can start with a few APs in one estate, then grow into multiple estates, better support triage, cleaner customer grouping and stronger planning without rebuilding the whole operation from scratch." },
      { type: "cta" },
    ],
  },
  {
    slug: "isp-automation-stack-2026",
    title: "The ISP Automation Stack for 2026: Billing, Routers, SMS, Support and Network Records Working Together",
    excerpt:
      "A simple playbook for modern ISPs that want payments, access control, support, staff actions and network records to move together instead of living in five tabs.",
    coverGradient: "from-orange-500 to-blue-700",
    coverImage: "https://images.unsplash.com/photo-1552664730-d307ca884978?auto=format&fit=crop&w=1400&q=75",
    coverImageAlt: "Team planning an operations workflow on a meeting table",
    category: "ISP Strategy",
    categoryColor: "orange",
    readTime: 6,
    publishedAt: "2026-09-29",
    updatedAt: "2026-09-29",
    author: editorialAuthor,
    tags: ["ISP Automation", "Billing", "Support", "Network Operations", "Internetily"],
    metaTitle: "ISP Automation Stack 2026 | Internetily",
    metaDescription:
      "Build a practical ISP automation stack for 2026: billing, payments, routers, SMS, support, logs and network records connected through Internetily.",
    keywords: [
      "ISP automation software",
      "ISP management system 2026",
      "internet provider operations",
      "ISP billing and support software",
      "router automation ISP",
      "M-Pesa ISP automation",
      "Internetily automation",
      "Netily ISP platform",
      "Splynx alternative",
      "Centipid alternative",
      "ISPMAN alternative",
      "WISPMAN alternative",
      "Jasiyo alternative",
    ],
    spatialCoverage: ["Kenya", "Uganda", "Tanzania", "South Africa", "United Kingdom", "United States", "Australia", "New Zealand"],
    toc: [
      { id: "why-stack", text: "Why a stack matters" },
      { id: "layers", text: "The core layers" },
      { id: "best-practice", text: "Best practice setup" },
      { id: "scale", text: "Scale with control" },
      { id: "internetily", text: "Internetily's advantage" },
    ],
    content: [
      { type: "p", html: "A modern ISP does not only need billing. It needs the billing record, payment status, router access, SMS reminder, support issue and staff action log to agree with each other. When those pieces live separately, customers feel the gaps quickly." },
      { type: "p", html: "The right automation stack is not about replacing people. It is about letting the team spend less time chasing proof of payment and more time improving the network, winning customers and supporting real issues." },
      { type: "h2", id: "why-stack", text: "Why an automation stack matters" },
      { type: "p", html: "A stack gives each system a clear job. Payments confirm money. Billing decides entitlement. RADIUS or router integration applies access. SMS and portals communicate with customers. Logs show who did what. Reports show whether the business is actually improving." },
      { type: "h2", id: "layers", text: "The core layers of a good ISP stack" },
      { type: "table", headers: ["Layer", "Job"], rows: [
        ["Customer and billing", "Plans, invoices, renewals, adjustments and subscription status."],
        ["Payments", "STK, Paybill, manual reconciliation and provider callbacks."],
        ["Network access", "PPPoE, hotspot, RADIUS, router and captive portal workflows."],
        ["Communication", "SMS, email, in-app notices and customer self-care."],
        ["Operations", "Support, staff permissions, audit logs and network asset records."],
      ] },
      { type: "h2", id: "best-practice", text: "Set it up with boring discipline" },
      { type: "ul", items: ["Use one customer record as the source of truth.", "Avoid manual payment actions without a reference and reason.", "Keep staff permissions tight and review them often.", "Send simple renewal and support messages customers understand.", "Reconcile reports weekly so small errors do not become big drama."] },
      { type: "h2", id: "scale", text: "Scale with control, not panic" },
      { type: "p", html: "Scaling an ISP is easier when every new estate, router, AP, OLT, customer plan and staff role has a home. You can start with a small customer base and still build the habit of clean records. That habit is what protects you when growth arrives." },
      { type: "callout", variant: "info", title: "Today's market rewards speed and trust", text: "Customers expect fast payment confirmation, clear renewal dates and support that remembers their account. Automation helps small teams look organised without pretending to be huge." },
      { type: "h2", id: "internetily", text: "How Internetily brings the stack together" },
      { type: "p", html: "Internetily brings billing, tenant subscriptions, hotspot, PPPoE, customer portals, staff access, SMS, support visibility and network operations into one practical platform for ISPs. The value is not only features. It is that the features are designed to work together around the way local providers actually operate." },
      { type: "p", html: "That makes Internetily useful for operators starting with a few customers and for larger tenants that need cleaner controls, better reporting and scalable day-to-day operations." },
      { type: "cta" },
    ],
  },
  {
    slug: "starting-small-as-an-isp-guide",
    title: "Starting Small as an ISP: A Friendly Field Guide for Your First Customers, Routers and Renewals",
    excerpt:
      "A practical guide for new internet providers: start with a focused area, simple packages, clean records, payment discipline and a system that can grow with you.",
    coverGradient: "from-emerald-600 to-orange-600",
    coverImage: "https://images.unsplash.com/photo-1497366754035-f200968a6e72?auto=format&fit=crop&w=1400&q=75",
    coverImageAlt: "Small team setting up a new business workspace",
    category: "ISP Startup",
    categoryColor: "emerald",
    readTime: 7,
    publishedAt: "2026-09-29",
    updatedAt: "2026-09-29",
    author: editorialAuthor,
    tags: ["Start an ISP", "WISP Startup", "ISP Billing", "Small ISP", "Internetily"],
    metaTitle: "How to Start Small as an ISP | Internetily Guide",
    metaDescription:
      "Learn how to start small as an ISP: choose a service area, design packages, set up billing, payments, routers, support and scale with Internetily.",
    keywords: [
      "how to start an ISP",
      "start a WISP",
      "small ISP setup",
      "internet provider startup",
      "estate WiFi business",
      "ISP billing for startups",
      "MikroTik ISP setup",
      "Internetily for small ISPs",
      "Netily ISP software",
      "start ISP Kenya",
      "start ISP Uganda",
      "start ISP Tanzania",
    ],
    spatialCoverage: ["Kenya", "Uganda", "Tanzania", "South Africa"],
    toc: [
      { id: "small-area", text: "Choose a small area" },
      { id: "packages", text: "Design simple packages" },
      { id: "operations", text: "Set up operations" },
      { id: "customers", text: "Win first customers" },
      { id: "scale", text: "Grow carefully" },
      { id: "internetily", text: "Use Internetily early" },
    ],
    content: [
      { type: "p", html: "Starting small as an ISP is not a weakness. It is often the smartest move. A focused estate, apartment block, school zone or business street lets you learn the network, support the customers and build cashflow without pretending you cover the whole country by Friday." },
      { type: "p", html: "The trick is to start small without starting messy. Clean records, clear packages and payment discipline matter from customer number one. Future-you will thank present-you with both hands." },
      { type: "h2", id: "small-area", text: "Choose an area you can actually serve well" },
      { type: "p", html: "Pick an area where installation is realistic, support is reachable and demand is visible. Talk to residents, shops, caretakers and landlords. Ask what they pay, what frustrates them and what support they wish existed." },
      { type: "ul", items: ["Map the buildings, lanes, poles or rooftops involved.", "Estimate backhaul, power and equipment costs honestly.", "Check competition and customer expectations.", "Start with an area your team can support quickly.", "Avoid selling service before the installation path is understood."] },
      { type: "h2", id: "packages", text: "Design packages customers understand" },
      { type: "p", html: "Simple packages sell better and support better. Use clear prices, speeds, durations and payment rules. If a package is daily, weekly or monthly, say what that means in real dates. If hotspot and PPPoE packages are different, keep them separate in the customer's mind." },
      { type: "table", headers: ["Package habit", "Why it helps"], rows: [
        ["Few starter plans", "Customers choose faster and support explains them easily."],
        ["Clear renewal rules", "Fewer disputes when the package expires."],
        ["Visible support contact", "Customers know where to go instead of shouting online."],
        ["Honest speeds", "Trust survives the first week."],
      ] },
      { type: "h2", id: "operations", text: "Set up the operating rhythm early" },
      { type: "ol", items: ["Create customer records before installation is complete.", "Record router, AP or ONU details during setup.", "Connect payment references to the right customer.", "Send renewal reminders before expiry.", "Review failed payments and inactive accounts every week.", "Keep staff roles clear even if the team is small."] },
      { type: "h2", id: "customers", text: "Win the first customers with local trust" },
      { type: "p", html: "Your first customers are your proof. Use local WhatsApp groups, posters, caretaker introductions, small demos and referrals. Keep the promise practical: where you serve, how much it costs, how installation works and how support reaches them." },
      { type: "p", html: "Do not hide behind fancy language. People want stable internet, fair pricing and someone who answers. That is a good offer." },
      { type: "h2", id: "scale", text: "Grow carefully once the basics work" },
      { type: "p", html: "Before entering the next area, check whether renewals are clean, support is under control and the current network is stable. Growth is sweet, but unstable growth is just a bigger queue of angry customers." },
      { type: "callout", variant: "tip", title: "Small ISP rule", text: "If you cannot explain who paid, who expired and which device serves them, pause expansion and fix the records first." },
      { type: "h2", id: "internetily", text: "Why Internetily helps from the beginning" },
      { type: "p", html: "Internetily helps new ISPs avoid the spreadsheet trap by giving them customer records, plans, billing, payments, hotspot and PPPoE workflows, SMS, staff access and reporting in one place. You can start lean and still build the habits of a serious provider." },
      { type: "p", html: "As the business grows, the same system can support more routers, tenants, payment workflows, customer communication and operational controls. That means you do not have to rebuild the business just when it starts working." },
      { type: "cta" },
    ],
  },
]
