import type { BlogPost } from "./blog-data"

export const operationsGuides: BlogPost[] = [
  {
    slug: "automate-wisp-billing-mpesa-auto-disconnect",
    title: "How to Automate WISP Billing and Auto-Disconnect Defaulters Using M-Pesa",
    excerpt: "Connect payment confirmation, subscription expiry and network access so your team spends less time chasing payments and reconnecting customers.",
    coverGradient: "from-emerald-600 to-blue-700",
    coverImage: "https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?auto=format&fit=crop&w=1400&q=75",
    coverImageAlt: "Customer making a payment at a checkout terminal",
    category: "Billing Automation",
    categoryColor: "emerald",
    readTime: 5,
    publishedAt: "2026-09-18",
    updatedAt: "2026-09-18",
    author: { name: "Netily Editorial Team", role: "ISP Operations", initials: "NT", avatarBg: "bg-emerald-600" },
    tags: ["WISP Billing", "M-Pesa", "PPPoE", "Kenya", "MikroTik"],
    metaTitle: "Automate WISP Billing & M-Pesa Renewals | Netily",
    metaDescription: "A practical guide to M-Pesa WISP billing: payment matching, PPPoE expiry, fair suspension, automatic reconnection and delayed-payment recovery.",
    keywords: ["automated WISP billing Kenya", "M-Pesa PPPoE renewals", "MikroTik auto disconnect unpaid users", "ISP payment reconciliation", "RADIUS subscriber suspension", "estate WiFi billing Nairobi", "WISP billing Mombasa", "Netily billing automation"],
    spatialCoverage: ["Kenya"],
    toc: [
      { id: "payment-to-access", text: "Connect payment to access" },
      { id: "billing-rules", text: "Set clear billing rules" },
      { id: "suspend-and-restore", text: "Suspend and restore access" },
      { id: "payment-recovery", text: "Handle delayed confirmations" },
      { id: "rollout", text: "Test before rollout" },
      { id: "faq", text: "Common questions" },
    ],
    content: [
      { type: "p", html: "To automate WISP billing with M-Pesa, match a confirmed payment to the correct subscriber, update their subscription, and apply the new access policy to your router or RADIUS service. At expiry, suspend unpaid service according to your published terms. Restore access when payment is verified. A payment prompt alone is not proof that money arrived." },
      { type: "p", html: "For an estate WiFi operator in Nairobi or a wireless ISP in Nakuru, the daily problem is familiar: a customer pays, sends a screenshot, and waits for someone to reconnect them. A reliable billing workflow removes that manual handoff while keeping a clear record of what happened." },
      { type: "h2", id: "payment-to-access", text: "Connect each payment to one subscriber" },
      { type: "ol", items: ["Give each customer a stable account reference. A phone number can help identify the payer, but a relative may pay on the customer's behalf.", "Create a payment attempt with the subscriber, selected package, expected amount and provider checkout reference.", "Receive and validate the provider's confirmation on the server. Match the amount and reference before crediting service.", "Record the receipt once, update the subscription and request network activation. Repeated callbacks must not add another month.", "Show payment and connection status in the customer portal so the subscriber can see whether access is ready."] },
      { type: "p", html: "Safaricom provides the payment APIs through <a href=\"https://daraja.safaricom.co.ke/\">Daraja</a>. Your production shortcode, callback endpoint and payment permissions need to be configured for the collection method you use. Keep credentials on the server." },
      { type: "h2", id: "billing-rules", text: "Agree on the billing rules before automating them" },
      { type: "p", html: "Decide whether a package runs for a fixed duration or renews on a calendar date. These are different promises: 30 days does not always end on the same day next month. State the expiry time, any grace period, and what an early or late payment buys. Display the same dates on the invoice, portal and reminder." },
      { type: "p", html: "Set a clear rule for partial payments and overpayments. A smaller payment should not silently unlock a full package. An extra payment should have a traceable credit or renewal outcome. Check pending payment confirmations before suspending a customer who may already have paid." },
      { type: "h2", id: "suspend-and-restore", text: "Suspend overdue service and restore it safely" },
      { type: "p", html: "Use the billing system as the source of truth for entitlement. Apply its decision through the configured MikroTik or RADIUS integration. Preventing a new login may not end an existing PPPoE session, so test session termination as well as authentication. A scheduled reconciliation should compare the intended access state with the actual network state." },
      { type: "callout", variant: "tip", title: "Keep a route back to payment", text: "Where your network supports it, let expired customers reach the renewal portal and required payment services. Test this from an expired account using mobile data switched off." },
      { type: "h2", id: "payment-recovery", text: "A slow confirmation must not become a second charge" },
      { type: "p", html: "If the callback is delayed, query the provider using the original checkout reference and retry activation when necessary. Tell the customer, 'We are checking your payment. Please do not pay again yet.' If payment is confirmed but the router is unreachable, show 'Payment received. Reconnecting your service.' Keep these states separate from a declined or cancelled payment." },
      { type: "h2", id: "rollout", text: "Test a small group before rolling out" },
      { type: "ul", items: ["Try a successful payment, cancellation, insufficient funds and a delayed callback.", "Send the same confirmation twice and check that the receipt and renewal appear only once.", "Disconnect a test router during activation, then confirm that recovery restores access.", "Test early renewal, expiry, grace periods and a payment from a different phone.", "Compare provider receipts, billing records and active sessions before expanding to the next group."] },
      { type: "h2", id: "faq", text: "Common questions about automated WISP billing" },
      { type: "h3", text: "Can I use the same workflow outside Kenya?" },
      { type: "p", html: "The payment-to-access pattern applies elsewhere, but the provider, currency and API agreement differ. A Kenyan Daraja integration should not be assumed to cover mobile money in Uganda or Tanzania. Confirm the local collection method before launch." },
      { type: "h3", text: "Should an unpaid subscriber be deleted?" },
      { type: "p", html: "No. Suspend access while keeping the subscriber's account, invoices and payment history. This makes renewal and dispute handling much easier." },
      { type: "p", html: "Explore <a href=\"/solutions/mpesa-isp-billing\">M-Pesa ISP billing with Netily</a>, then plan the customer journey with our <a href=\"/blog/self-care-captive-portal-isp-renewals\">self-care captive portal guide</a>." },
      { type: "cta" },
    ],
  },
  {
    slug: "mixed-vendor-isp-hardware-tr069-smartolt-2026",
    title: "The 2026 Guide to Managing Mixed-Vendor ISP Hardware with TR-069 and SmartOLT",
    excerpt: "Understand where TR-069, an ACS and SmartOLT fit, then build a practical compatibility and provisioning checklist for your fibre and wireless network.",
    coverGradient: "from-blue-600 to-purple-700",
    coverImage: "https://images.unsplash.com/photo-1558494949-ef010cbdcc31?auto=format&fit=crop&w=1400&q=75",
    coverImageAlt: "Rows of server cabinets in a data centre",
    category: "Network Operations",
    categoryColor: "blue",
    readTime: 5,
    publishedAt: "2026-09-18",
    updatedAt: "2026-09-18",
    author: { name: "Netily Editorial Team", role: "ISP Operations", initials: "NT", avatarBg: "bg-blue-600" },
    tags: ["TR-069", "SmartOLT", "FTTH", "CPE Management", "ISP Operations"],
    metaTitle: "TR-069 & SmartOLT: Mixed-Vendor ISP Guide 2026 | Netily",
    metaDescription: "Plan mixed-vendor ISP operations with TR-069, ACS and SmartOLT: device compatibility, subscriber mapping, secure provisioning and rollout checks.",
    keywords: ["TR-069 ISP management", "SmartOLT network management", "mixed vendor ISP hardware", "ACS CPE provisioning", "Huawei ZTE OLT management", "FTTH subscriber provisioning Kenya", "fibre ISP operations South Africa", "WISP device management"],
    spatialCoverage: ["Kenya", "Uganda", "Tanzania", "South Africa"],
    toc: [
      { id: "different-jobs", text: "What each tool does" },
      { id: "compatibility", text: "Check device compatibility" },
      { id: "subscriber-mapping", text: "Connect devices to subscribers" },
      { id: "secure-rollout", text: "Roll out safely" },
      { id: "regional-operations", text: "Plan for local operations" },
      { id: "faq", text: "Common questions" },
    ],
    content: [
      { type: "p", html: "TR-069 and SmartOLT solve different parts of ISP device management. TR-069 lets an Auto Configuration Server (ACS) manage compatible customer equipment. SmartOLT focuses on supported optical line terminals and connected optical network units. Your billing system links a subscriber's paid service to the access policy; it does not replace either management layer." },
      { type: "p", html: "A growing ISP may have MikroTik at the edge, Huawei or ZTE equipment in the fibre network, and several customer router brands. The aim is not to make every device behave identically. It is to know which system owns each setting and how your team checks that a change worked." },
      { type: "h2", id: "different-jobs", text: "Give each system a clear job" },
      { type: "table", headers: ["Layer", "Main job", "What to verify"], rows: [
        ["Billing and RADIUS", "Subscriber entitlement, package and access policy", "Payment confirmation, expiry and session enforcement"],
        ["TR-069 and ACS", "Remote configuration and diagnostics for compatible CPE", "Supported parameters, firmware and device reachability"],
        ["SmartOLT", "Management of supported OLTs and ONUs", "Exact OLT model, firmware, line cards and ONU behaviour"],
        ["Network monitoring", "Availability, capacity and service health", "Useful alerts and an owner for each incident"],
      ] },
      { type: "p", html: "The <a href=\"https://www.broadband-forum.org/certifications/bbf-069-certification/\">Broadband Forum describes TR-069</a> as a protocol for remote provisioning and lifecycle management of customer equipment. The <a href=\"https://cwmp-data-models.broadband-forum.org/\">CWMP data models</a> describe the parameters involved. Device support still needs to be checked for your exact hardware and firmware." },
      { type: "h2", id: "compatibility", text: "Build a compatibility list before buying hardware" },
      { type: "p", html: "Record the manufacturer, model, firmware, serial number and management method for each device family. On a test unit, read the parameters you need and apply a harmless change. Confirm that it persists after reboot and that your ACS reports failures clearly. A TR-069 label on a box does not guarantee every feature you want." },
      { type: "p", html: "<a href=\"https://www.smartolt.com/index.html\">SmartOLT lists support for ZTE and Huawei OLT families</a>, including ZTE C300/C320 and Huawei MA58xx/MA56xx. Verify the particular model, software release and required operations with the supplier. This guide describes a deployment approach; confirm the Netily integration scope for your equipment before purchasing or migrating." },
      { type: "h2", id: "subscriber-mapping", text: "Link the subscriber, service and device records" },
      { type: "p", html: "Keep a stable subscriber ID connected to the PPPoE username, ONU serial number, OLT port and customer router record. Avoid using a customer's name as the only link. A household may replace its router or move premises while keeping the same billing account." },
      { type: "ol", items: ["Create the customer and choose the service package.", "Identify the installed ONU and CPE, then attach them to the service record.", "Apply approved provisioning profiles through the relevant management system.", "Verify connectivity, bandwidth and monitoring before marking installation complete.", "Record who changed a profile and retain the previous value where it can be recovered safely."] },
      { type: "h2", id: "secure-rollout", text: "Make changes in small, recoverable batches" },
      { type: "p", html: "Protect management access with restricted networks, unique credentials and HTTPS where supported. Keep secrets out of browser code and support notes. Export working configurations before a firmware or profile change, and test rollback on spare equipment. Start with staff connections before changing an entire estate." },
      { type: "callout", variant: "warning", title: "Avoid two systems writing the same setting", text: "If an ACS and an OLT profile both control a service parameter, decide which one owns it. Conflicting templates can repeatedly undo a technician's changes." },
      { type: "h2", id: "regional-operations", text: "Match the workflow to your support coverage" },
      { type: "p", html: "Whether you serve Nairobi estates, Kampala neighbourhoods, Dar es Salaam businesses or South African fibre customers, stock availability and technician coverage shape your hardware choices. Standardise a few tested models, keep spares and document how to replace a device without losing its subscriber mapping. Check local billing, currency and payment requirements separately from hardware compatibility." },
      { type: "h2", id: "faq", text: "Common questions about mixed-vendor management" },
      { type: "h3", text: "Does SmartOLT replace a TR-069 ACS?" },
      { type: "p", html: "Do not assume so. OLT and ONU management and customer-router management have different scopes. Choose the tools based on the operations each device needs and validate how they work together." },
      { type: "h3", text: "Will TR-069 work with every customer router?" },
      { type: "p", html: "No. The device must support the protocol and the required parameters, and it must be configured to reach your ACS. Test each model and firmware combination you intend to deploy." },
      { type: "p", html: "Read about <a href=\"/solutions/mikrotik-billing-software\">MikroTik billing workflows</a> and <a href=\"/blog/automate-wisp-billing-mpesa-auto-disconnect\">payment-driven subscriber access</a> before designing your provisioning handoff." },
      { type: "cta" },
    ],
  },
  {
    slug: "self-care-captive-portal-isp-renewals",
    title: "How to Build a Self-Care Captive Portal That Reduces ISP Support Calls and Automates Renewals",
    excerpt: "Give subscribers a clear path from expired access to payment and reconnection, with mobile-friendly package selection and honest payment updates.",
    coverGradient: "from-orange-500 to-purple-700",
    coverImage: "https://images.unsplash.com/photo-1516321318423-f06f85e504b3?auto=format&fit=crop&w=1400&q=75",
    coverImageAlt: "People using a laptop together at a desk",
    category: "Customer Experience",
    categoryColor: "orange",
    readTime: 5,
    publishedAt: "2026-09-18",
    updatedAt: "2026-09-18",
    author: { name: "Netily Editorial Team", role: "ISP Operations", initials: "NT", avatarBg: "bg-orange-600" },
    tags: ["Captive Portal", "Customer Self-Service", "Hotspot", "Renewals", "M-Pesa"],
    metaTitle: "Self-Care Captive Portals & ISP Renewals | Netily",
    metaDescription: "Build a mobile-friendly ISP captive portal with clear packages, M-Pesa payment feedback, automatic renewal recovery and useful customer support options.",
    keywords: ["self care captive portal", "ISP customer self service", "hotspot M-Pesa renewals", "MikroTik captive portal Kenya", "reduce ISP billing support calls", "PPPoE customer portal", "WiFi billing Uganda", "hotspot billing Tanzania", "ISP subscriber portal South Africa"],
    spatialCoverage: ["Kenya", "Uganda", "Tanzania", "South Africa"],
    toc: [
      { id: "first-screen", text: "Make the first screen useful" },
      { id: "renewal-journey", text: "Design the renewal journey" },
      { id: "payment-feedback", text: "Explain payment progress" },
      { id: "mobile-access", text: "Test real mobile access" },
      { id: "measure", text: "Measure support demand" },
      { id: "faq", text: "Common questions" },
    ],
    content: [
      { type: "p", html: "A useful self-care captive portal lets a customer identify their account, understand the package price and duration, pay, and see when access is restored. It should also explain what to do when payment is delayed. Those everyday answers can reduce avoidable calls without hiding your support team." },
      { type: "p", html: "A captive portal and an account portal are related but different. The captive portal handles access when a device joins a hotspot. An authenticated customer portal provides account history and renewals. PPPoE customers generally need the latter; they should not have to use a hotspot login to manage their home connection." },
      { type: "h2", id: "first-screen", text: "Put the customer's next step on the first screen" },
      { type: "ul", items: ["Show the ISP name and logo so the customer recognises the network.", "Display the current package, expiry date and access status after the customer is identified.", "Show package price, currency, duration, speed and relevant limits before payment.", "Keep Renew or Buy a package easy to find, with a separate support contact.", "Use clear text, readable contrast and large touch targets on a narrow screen."] },
      { type: "p", html: "Avoid making a returning subscriber re-enter details you already have. Preselect the current package where appropriate and let them confirm or change the payment phone number. Never expose another household's account simply because someone knows its phone number." },
      { type: "h2", id: "renewal-journey", text: "Keep renewal short and predictable" },
      { type: "ol", items: ["Show the package and full payable amount, including any applicable charges.", "Explain when the renewed service starts and ends, especially for an early renewal.", "Let the customer confirm the payer's number and request the payment prompt once.", "Keep the payment attempt available when the page is refreshed or reopened.", "After confirmed payment, show the receipt and the actual service state. Offer a clear way back online."] },
      { type: "p", html: "For a Kenyan M-Pesa checkout, ask the customer to approve the prompt on their phone. Never ask for the M-Pesa PIN inside the portal. For Uganda, Tanzania or South Africa, use the relevant supported local payment provider and currency. Do not present a payment option until it is connected and tested." },
      { type: "h2", id: "payment-feedback", text: "Explain what is happening after the customer pays" },
      { type: "table", headers: ["State", "Customer message", "Useful action"], rows: [
        ["Prompt requested", "Check your phone to approve the payment.", "Wait for confirmation"],
        ["Confirmation delayed", "We are checking your payment. Please do not pay again yet.", "Check payment status"],
        ["Payment confirmed, activation pending", "Payment received. Reconnecting your service.", "Keep checking access and offer support"],
        ["Access verified", "You are connected. Your package is active.", "Continue browsing"],
        ["Payment cancelled or declined", "The payment was not completed.", "Retry or choose another supported method"],
      ] },
      { type: "p", html: "A waiting timer can change the message after about 30 seconds, but it must not turn an unknown result into a failed payment. Keep checking the original attempt on the server. If the network is slow, let the customer leave and return without losing progress or creating another charge." },
      { type: "h2", id: "mobile-access", text: "Test the portal from an expired connection" },
      { type: "p", html: "Test on Android and iPhone, in both the captive-network window and a normal browser. Switch mobile data off. Confirm that the portal, payment dependencies and required assets are reachable before login. Keep the allowed destinations limited to what the renewal journey actually needs." },
      { type: "ul", items: ["Check a small screen with the keyboard open and at increased text size.", "Ensure a long package list and payment dialog can scroll without hiding the submit button.", "Try a slow connection, refresh during payment and a lost callback.", "Use lightweight images and avoid autoplay video on the payment screen.", "Show a support reference when activation needs help, without exposing payment credentials or other customers' details."] },
      { type: "h2", id: "measure", text: "Measure whether customers need less help" },
      { type: "p", html: "Record a baseline of billing-related support requests before launching. Then track renewal completion, abandoned payment attempts, time from confirmed payment to access, and repeat contacts per subscriber. Group complaints such as 'I paid but cannot connect' separately from coverage or speed problems. Compare similar periods rather than promising a fixed reduction in calls." },
      { type: "h2", id: "faq", text: "Common questions about self-care portals" },
      { type: "h3", text: "Can an expired customer renew without mobile data?" },
      { type: "p", html: "Yes, if the network is configured to allow the portal and the necessary payment dependencies before authentication. Verify this on the actual router and devices you serve." },
      { type: "h3", text: "Will a portal remove every support call?" },
      { type: "p", html: "No. It can handle routine renewal questions, but customers still need help with faults, disputes and unusual payments. Keep a visible support route and pass along the account and payment reference where appropriate." },
      { type: "p", html: "Explore <a href=\"/solutions/hotspot-billing-software-kenya\">Netily hotspot billing</a> and the <a href=\"/blog/automate-wisp-billing-mpesa-auto-disconnect\">M-Pesa billing automation guide</a> to connect the portal experience to subscriber access." },
      { type: "cta" },
    ],
  },
]
