name: Deploy to DigitalOcean VPS

# This tells GitHub to run this script ONLY when you push to the prod-backend branch
on:
  push:
    branches:
      - prod-frontend

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to VPS
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            # 1. Go to the frontend folder
            cd ~/netily-frontend
            
            # 2. Pull the newest code
            git fetch origin prod-frontend
            git reset --hard origin/prod-frontend
            
            # 3. Rebuild and restart the Next.js container
            docker compose up -d --build
            
            # 4. Clean up old unused Docker images to save disk space
            docker image prune -f
            
            echo "Next.js Frontend is live on Port 3000!"